-- MySQL Script generated by MySQL Workbench
-- Sun Apr 22 11:18:22 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`reimb_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reimb_type` (
  `type_id` INT NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `percentage` INT NOT NULL,
  PRIMARY KEY (`type_id`))
ENGINE = TokuDB;


-- -----------------------------------------------------
-- Table `mydb`.`grading_style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grading_style` (
  `style_id` INT NOT NULL,
  `style` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`style_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`progress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`progress` (
  `progress_id` INT NOT NULL,
  `progress` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`progress_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `emp_id` INT NOT NULL,
  `first_name` VARCHAR(15) NOT NULL,
  `last_name` VARCHAR(15) CHARACTER SET 'big5' COLLATE 'big5_bin' NOT NULL,
  `amount_left` DECIMAL(2) NOT NULL,
  `email` VARCHAR(65) NULL,
  `department_dept_id` INT NOT NULL,
  `super_id` INT NOT NULL,
  `dept_head_id` INT NOT NULL,
  PRIMARY KEY (`emp_id`),
  INDEX `fk_employee_employee1_idx` (`super_id` ASC),
  INDEX `fk_employee_employee2_idx` (`dept_head_id` ASC),
  CONSTRAINT `fk_employee_employee1`
    FOREIGN KEY (`super_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_employee2`
    FOREIGN KEY (`dept_head_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`claims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`claims` (
  `claims_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `description` VARCHAR(250) NULL,
  `justification` VARCHAR(250) NULL,
  `attachment` BLOB NULL,
  `projected_amount` DECIMAL(2) NOT NULL,
  `adjusted_amount` DECIMAL(2) NULL,
  `submitted` TIMESTAMP NOT NULL,
  `type_id` INT NOT NULL,
  `style_id` INT NOT NULL,
  `progress_id` INT NOT NULL,
  `submitter_id` INT NOT NULL,
  `supervisor_id` INT NOT NULL,
  `supervisor_resolved` TIMESTAMP NULL,
  `super_email` BLOB NULL,
  `head_id` INT NOT NULL,
  `head_resolved` TIMESTAMP NULL,
  `head_email` BLOB NULL,
  `benco_id` INT NOT NULL,
  `benco_resolved` TIMESTAMP NULL,
  `benco_email` BLOB NULL,
  `proof_of_passing` BLOB NULL,
  PRIMARY KEY (`claims_id`),
  UNIQUE INDEX `claims_id_UNIQUE` (`claims_id` ASC),
  INDEX `fk_claims_reimb_type_idx` (`type_id` ASC),
  INDEX `fk_claims_grading_style1_idx` (`style_id` ASC),
  INDEX `fk_claims_progress1_idx` (`progress_id` ASC),
  INDEX `fk_claims_employee1_idx` (`submitter_id` ASC),
  INDEX `fk_claims_employee2_idx` (`supervisor_id` ASC),
  INDEX `fk_claims_employee3_idx` (`head_id` ASC),
  INDEX `fk_claims_employee4_idx` (`benco_id` ASC),
  CONSTRAINT `fk_claims_reimb_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`reimb_type` (`type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claims_grading_style1`
    FOREIGN KEY (`style_id`)
    REFERENCES `mydb`.`grading_style` (`style_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claims_progress1`
    FOREIGN KEY (`progress_id`)
    REFERENCES `mydb`.`progress` (`progress_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claims_employee1`
    FOREIGN KEY (`submitter_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claims_employee2`
    FOREIGN KEY (`supervisor_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claims_employee3`
    FOREIGN KEY (`head_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_claims_employee4`
    FOREIGN KEY (`benco_id`)
    REFERENCES `mydb`.`employee` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
